from pydantic import BaseModel, Field
from typing import Any, List, Dict


class QueryRequest(BaseModel):
    """Incoming request body for natural language to SQL."""
    query: str = Field(..., min_length=1, description="Natural language question to translate into SQL")


class SqlResponse(BaseModel):
    """Intermediate response containing the SQL generated by the LLM."""
    sql: str


class QueryResponse(BaseModel):
    """Final response containing query results."""
    results: List[Dict[str, Any]]
    sql: str | None = None


