from pydantic import BaseModel, Field
from typing import Any, List, Dict, Optional


class QueryRequest(BaseModel):
    """Incoming request body for natural language to SQL."""
    query: str = Field(..., min_length=1, description="Natural language question to translate into SQL")


class SqlResponse(BaseModel):
    """Intermediate response containing the SQL generated by the LLM."""
    sql: str


class QueryResponse(BaseModel):
    """Final response containing query results."""
    results: List[Dict[str, Any]]
    sql: str | None = None


# Quote generation schemas
class QuoteItemRequest(BaseModel):
    """Individual item in a quote request."""
    sku: str
    description: str
    quantity: int
    unit_price: float
    currency: str
    subtotal: float
    product_id: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = None
    position: Optional[int] = None


class QuoteRequest(BaseModel):
    """Request for quote creation."""
    prompt: str = Field(..., min_length=1, description="Natural language description of camera/accessory needs")
    title: Optional[str] = Field(None, description="Optional title for the quote")
    currency: Optional[str] = Field(None, description="Currency for the quote")
    items: List[QuoteItemRequest] = Field(..., description="List of items in the quote")
    notes: Optional[str] = Field(None, description="Optional notes for the quote")
    extracted_intent: Optional[Dict[str, Any]] = Field(None, description="Extracted intent from the prompt")
    feedback: Optional['QuoteFeedbackRequest'] = Field(None, description="Optional feedback to include with quote creation")

class QuoteItemResponse(BaseModel):
    """Individual item in a quote response."""
    id: str
    sku: str
    description: str
    quantity: int
    unit_price: float
    currency: str
    subtotal: float
    product_id: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = None
    position: Optional[int] = None
    created_at: str
    feedback_insights: Optional[Dict[str, Any]] = None  # Aggregated feedback insights for this item
class QuoteResponse(BaseModel):
    """Response containing generated quote."""
    id: str
    title: Optional[str] = None
    prompt: str
    extracted_intent: Optional[Dict[str, Any]] = None
    currency: Optional[str] = None
    total_amount: Optional[float] = None
    notes: Optional[str] = None
    status: str
    created_at: str
    updated_at: str
    items: List[QuoteItemResponse]





class QuoteListResponse(BaseModel):
    """Response for listing quotes."""
    quotes: List[QuoteResponse]
    total: int


class QuoteFeedbackRequest(BaseModel):
    """Request for quote feedback."""
    rating: Optional[int] = Field(None, ge=1, le=5, description="Rating from 1 to 5")
    comment: Optional[str] = None
    labels: Optional[Dict[str, Any]] = None
    corrections: Optional[Dict[str, Any]] = None


class QuoteFeedbackResponse(BaseModel):
    """Response for quote feedback."""
    id: str
    quote_id: str
    rating: Optional[int] = None
    comment: Optional[str] = None
    labels: Optional[Dict[str, Any]] = None
    corrections: Optional[Dict[str, Any]] = None
    created_at: str


class QuoteItemFeedbackRequest(BaseModel):
    """Request for item-level feedback."""
    feedback_type: str = Field(..., description="Type of feedback: correct, incorrect, missing, wrong_quantity, wrong_price, wrong_specs")
    comment: Optional[str] = Field(None, description="Detailed comment about the item")
    suggested_sku: Optional[str] = Field(None, description="Suggested SKU if the current one is wrong")
    suggested_quantity: Optional[int] = Field(None, ge=1, description="Suggested quantity if wrong")
    suggested_price: Optional[float] = Field(None, ge=0, description="Suggested price if wrong")
    correction_data: Optional[Dict[str, Any]] = Field(None, description="Structured correction data")
    user_context: Optional[Dict[str, Any]] = Field(None, description="Additional context about why this item was wrong")


class QuoteItemFeedbackResponse(BaseModel):
    """Response for item-level feedback."""
    id: str
    quote_item_id: str
    quote_id: str
    feedback_type: str
    rating: Optional[int] = None
    comment: Optional[str] = None
    suggested_sku: Optional[str] = None
    suggested_quantity: Optional[int] = None
    suggested_price: Optional[float] = None
    correction_data: Optional[Dict[str, Any]] = None
    user_context: Optional[Dict[str, Any]] = None
    created_at: str
    updated_at: str


